// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpgbsnwmlkfurbbqbpnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwZ2JzbndtbGtmdXJiYnFicG5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NjUxMzMsImV4cCI6MjA3NDU0MTEzM30.8s2JeTt8VGJvbxLMTgBub9ijVUx35eOgJzvpkmVmhJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});